# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b70357e45e37cab8c867ae5f0010443e7a679cc53535f2f23f96359178cfdb8eaceefa1d8fec124b3bca0fb01276d82ad862eea9a5743da84e59947c49ce32c

test:
  secret_key_base: bbe414b39eac5ea0dff0f5812c0f48707ee4e3ae0cdfcd5992b2592c0c8b16c6bf9802b984f38cc428aafa6a05a0c74cf12f39bd9e819db3131ce588fb9dba3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
